### ISSUE TITLE
Answers get pasted but doesn't gets posted

### ISSUE THREAD

**Issue by Mr-Nobody1** [harmindersinghnijjar/quora-qa-automation#7]
Error while selecting answer credential:  Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="root"]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div[1]/div[3]/div[1]/div/label/div/div[2]/div/span/span[2]"}
  (Session info: chrome=112.0.5615.138)

**Comment by Mr-Nobody1** [comment]
Error while pasting answer into text box:  Message: timeout: Timed out receiving message from renderer: 20.000
  (Session info: chrome=112.0.5615.138)

getting this even though answer gets pasted

**Comment by Mr-Nobody1** [comment]
answers is pastedError while clicking on answer popup button:  Message: element click intercepted: Element <button class="q-click-wrapper qu-active--textDecoration--none qu-focus--textDecoration--none qu-disabled qu-borderRadius--pill qu-alignItems--center qu-justifyContent--center qu-whiteSpace--nowrap qu-userSelect--none qu-display--inline-flex qu-tapHighlight--white qu-textAlign--center qu-cursor--pointer qu-hover--textDecoration--none qu-hover--bg--darken ClickWrapper___StyledClickWrapperBox-zoqi4f-0 iyYUZT base___StyledClickWrapper-lx6eke-1 fJHGyh  " role="button" type="button" tabindex="0" style="box-sizing: border-box; font: inherit; padding: 0px 20px 0px 12px; transition-property: box-shadow, background-color; transition-duration: 60ms; transition-timing-function: ease-out; height: 38px; min-width: 38px; position: relative; box-shadow: rgba(99, 100, 102, 0.2) 0px 0px 0px 1px inset; border-width: 0px; outline: none; color: inherit; background-color: transparent;" disabled="" aria-disabled="true">...</button> is not clickable at point (471, 232). Other element would receive the click: <div class="content">...</div>
  (Session info: chrome=112.0.5615.138)

**Comment by Mr-Nobody1** [comment]
If I use another machine I get this error
Do we have enough room for all the BLM that's about to go to jail?
Error while pasting answer into text box:  Message: no such element: Unable to locate element: {"method":"css selector","selector":"#root > div > div:nth-child(2) > div > div > div > div > div.q-flex.ModalContainerInternal___StyledFlex-s8es4q-2.gXhqYs.modal_content_inner.qu-flexDirection--column.qu-bg--white.qu-overflowY--auto.qu-borderAll.qu-alignSelf--center > div > div.q-flex.qu-flexDirection--column.qu-overflowY--auto > div.q-relative.qu-display--flex.qu-flexDirection--column > div > div.q-box > div:nth-child(2) > div > div > div > div > div.q-box > div"}

desn't even get pasted and refreshes

**Comment by harmindersinghnijjar** [comment]
> Error while selecting answer credential: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="root"]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div[1]/div[3]/div[1]/div/label/div/div[2]/div/span/span[2]"} (Session info: chrome=112.0.5615.138)

This is likely happening because the XPATH I provided is specific to my account. I could change it from XPATH to CSS Selector to make it more generic and replicable.

**Comment by harmindersinghnijjar** [comment]
> Error while selecting answer credential: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="root"]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div[1]/div[3]/div[1]/div/label/div/div[2]/div/span/span[2]"} (Session info: chrome=112.0.5615.138)

This is likely happening because the XPATH I provided is specific to my account. I can change it from XPATH to CSS Selector to make it more generic and replicable.

**Comment by Mr-Nobody1** [comment]
done but now am facing this error again 
```Error while pasting answer into text box:  Message: timeout: Timed out receiving message from renderer: 20.000```
on another pc

**Comment by harmindersinghnijjar** [comment]
Does it mention what line number in the code the error is on? It would help if you posted a screenshot of the command prompt when it runs into the error. That would give me more insight into the issue.

**Comment by Mr-Nobody1** [comment]
![image](https://user-images.githubusercontent.com/73386704/235319507-f20812a9-d2f4-46dc-90f8-7e63b9b5e511.png)

**Comment by harmindersinghnijjar** [comment]
I made some adjustments to the code. Please try to run the script with the updated quora_automation.py file. 

If you run into this particular error again, the script will attempt to skip the question on which it received the error and answer the next question.

**Comment by Mr-Nobody1** [comment]
![image](https://user-images.githubusercontent.com/73386704/235322364-81d488e3-c760-416a-b568-794634d0ad8e.png)
![image](https://user-images.githubusercontent.com/73386704/235322366-26ef1e75-0753-4685-8b1d-62898a123d7f.png)

**Comment by Mr-Nobody1** [comment]
> done but now am facing this error again `Error while pasting answer into text box: Message: timeout: Timed out receiving message from renderer: 20.000` on another pc

Why is this happening in the first place?

**Comment by Mr-Nobody1** [comment]
even tried with edge. same error!

**Comment by Mr-Nobody1** [comment]
can we use this script in ubuntu ?

**Comment by harmindersinghnijjar** [comment]
Frankly, I'm not entirely sure. The script seems to be waiting for a particular action to occur on the webpage. When it doesn't, it meets a timeout limit.

I added the following lines of code in an attempt to correct the issue: 

`# In order to prevent the "Timed out receiving message from renderer: 20.000" error, add the following options.
                options.add_experimental_option('extensionLoadTimeout', 60000)`

**Comment by harmindersinghnijjar** [comment]
> can we use this script in ubuntu ?

I've only ever used it with Google Chrome.

**Comment by Mr-Nobody1** [comment]
> > can we use this script in ubuntu ?
> 
> I've only ever used it with Google Chrome.

Linux operating system?

**Comment by harmindersinghnijjar** [comment]
> > > can we use this script in ubuntu ?
> > 
> > 
> > I've only ever used it with Google Chrome.
> 
> Linux operating system?

Only on Google Chrome with Windows.

**Comment by Mr-Nobody1** [comment]
I noticed one thing that when the script opens the tab. I cannot post my question for some reason why even if I press the post button manually?

**Comment by harmindersinghnijjar** [comment]
If you're wanting to, we can Zoom sometime and try and get the bot working for you.

**Comment by Mr-Nobody1** [comment]
yes, we can. you can tell me whenever you are free

**Comment by Mr-Nobody1** [comment]
![image](https://user-images.githubusercontent.com/73386704/235338226-ccdc00c7-24c5-412e-9828-8c5621066f91.png)

**Comment by Mr-Nobody1** [comment]
`self.set_page_load_timeout(20)` to `self.set_page_load_timeout(50)` fixed it for me
Giving it some extra time to load fixed it but I am still not entirely sure!
